GET http://localhost:8080/api/users/me
Accept: application/json

###
POST http://localhost:8080/api/login
Accept: application/json

{
  "username":"admin",
  "password":"123321"
}

###
GET http://localhost:8080/api/logout
Accept: application/json

###