POST http://localhost:8080/api/login
Accept: application/json

{
  "username":"admin",
  "password":"1234abc"
}

###
GET http://localhost:8080/api/users/me
Accept: application/json

###
GET http://localhost:8080/api/logout
Accept: application/json

###
GET http://localhost:8080/api/users/1

###
GET http://localhost:8080/api/users?page=1&size=2

###
GET http://localhost:8080/api/accidents/1

###
GET http://localhost:8080/api/accidents?page=1&size=10