spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
  datasource:
    url: jdbc:postgresql://jktu.cc:5432/gis
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 60000
  sql:
    init:
      schema-locations: classpath:/sql/schema.sql
      #      mode: always
      data-locations: classpath:/sql/data.sql

mybatis-plus:
  global-config:
    banner: false
  type-enums-package: cc.jktu.gis.model.constant

logging:
  level:
    "org.springframework.web": debug
    "org.springframework.security": debug

server:
  servlet:
    session:
      persistent: true